const DASHBOARD = `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sensex Signal Engine</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#101214;color:#e8eaed;font-family:Arial,sans-serif}header{display:flex;justify-content:space-between;align-items:center;padding:22px 28px;background:#15181b;border-bottom:1px solid #292d32}h1{margin:0;font-size:22px}header p{margin:5px 0 0;color:#8d96a0;font-size:13px}#status{color:#65d18a}main{max-width:1600px;margin:auto;padding:24px 28px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card,.panel{background:#171a1e;border:1px solid #292d32;border-radius:10px}.card{padding:18px;min-height:110px}label{display:block;color:#8d96a0;font-size:12px;letter-spacing:1px}.value{display:block;margin-top:14px;font-size:26px;font-weight:700}.panel{margin-top:18px;padding:18px}.panel h2{font-size:16px;margin:0 0 15px}.small{float:right;color:#8d96a0;font-weight:normal;font-size:12px}#details{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.detail{background:#111417;padding:12px;border-radius:7px}.detail span{display:block;color:#8d96a0;font-size:12px}.detail b{display:block;margin-top:5px;font-size:15px}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:1450px}th,td{text-align:left;padding:10px 8px;border-bottom:1px solid #292d32;font-size:12px;white-space:nowrap}th{color:#8d96a0;font-weight:500}.bullish,.bull{color:#65d18a}.bearish,.bear{color:#ff7070}.watch,.neutral{color:#f0c674}.good{color:#65d18a}.muted{color:#8d96a0}@media(max-width:1100px){.cards{grid-template-columns:repeat(2,1fr)}#details{grid-template-columns:repeat(3,1fr)}}
</style></head>
<body><header><div><h1>SENSEX SIGNAL ENGINE</h1><p>Stage 2 · 1-minute market-state collection</p></div><span id="status">Connecting...</span></header>
<main><section class="cards"><div class="card"><label>PRICE</label><strong id="price" class="value">—</strong></div><div class="card"><label>RSI</label><strong id="rsi" class="value">—</strong></div><div class="card"><label>TREND</label><strong id="trend" class="value">—</strong></div><div class="card"><label>VOLUME</label><strong id="volumeState" class="value">—</strong></div></section>
<section class="panel"><h2>Latest Market Snapshot <span id="updated" class="small"></span></h2><div id="details">Waiting for TradingView snapshot...</div></section>
<section class="panel"><h2>Snapshot History <span class="small">Auto-refresh: 3 sec · latest 50</span></h2><div class="tablewrap"><table><thead><tr><th>Time</th><th>Price</th><th>RSI</th><th>Trend</th><th>Vol State</th><th>Vol Ratio</th><th>VWAP</th><th>VWAP Dist</th><th>OR</th><th>VPC</th><th>ADR %</th><th>VIX</th><th>Session</th><th>ATM</th></tr></thead><tbody id="history"></tbody></table></div></section>
<section class="panel"><h2>Raw Signal Events <span class="small">Includes OR_BREAKOUT and other alerts</span></h2><div class="tablewrap"><table><thead><tr><th>Time</th><th>Event</th><th>Price</th><th>High</th><th>Low</th><th>Volume</th><th>Bias</th></tr></thead><tbody id="events"></tbody></table></div></section>
</main>
<script>
const $=id=>document.getElementById(id);const n=v=>v==null||v===""?"—":Number(v).toLocaleString("en-IN",{maximumFractionDigits:2});const t=v=>v?new Date(v).toLocaleTimeString("en-IN",{hour12:false}):"—";const txt=v=>v==null||v===""?"—":String(v);const cls=v=>String(v||"").toLowerCase().replace(/\\s+/g,"-");
function detail(label,value,c=""){return '<div class="detail"><span>'+label+'</span><b class="'+c+'">'+txt(value)+'</b></div>'}
async function refresh(){try{const d=await (await fetch("/api/signals?limit=50",{cache:"no-store"})).json();const rows=d.signals||[];$('status').textContent="● LIVE";$('status').style.color="#65d18a";if(!rows.length){$('details').textContent="Waiting for TradingView snapshot...";$('history').innerHTML="";$('events').innerHTML="";return}const s=rows[0],p=s.raw_payload||{},trend=String(p.trend||"");$('price').textContent=n(s.price);$('rsi').textContent=n(p.rsi);$('trend').textContent=txt(p.trend);$('trend').className="value "+(trend==="BULL"?"bull":trend==="BEAR"?"bear":"neutral");$('volumeState').textContent=txt(p.volume_state);$('volumeState').className="value "+(String(p.volume_state||"")==="HIGH"?"good":String(p.volume_state||"")==="LOW"?"neutral":"");$('updated').textContent="Received "+t(s.received_at);
$('details').innerHTML=[detail("Ticker",s.ticker),detail("Exchange",s.exchange),detail("Price",n(s.price)),detail("RSI",n(p.rsi)),detail("Trend",p.trend,trend==="BULL"?"bull":trend==="BEAR"?"bear":"neutral"),detail("Volume state",p.volume_state),detail("Volume ratio",n(p.volume_ratio)),detail("VWAP",p.vwap),detail("VWAP distance",n(p.vwap_distance)),detail("OR state",p.or_state),detail("OR high",n(p.or_high)),detail("OR low",n(p.or_low)),detail("VPC zone",p.vpc_zone),detail("VPC mid",n(p.vpc_mid)),detail("ADR used %",n(p.adr_used_pct)),detail("VIX",n(p.vix)),detail("Session",p.session),detail("ATM strike",n(p.atm_strike)),detail("Event time",t(s.event_time))].join("");
$('history').innerHTML=rows.filter(r=>r.event==="MARKET_SNAPSHOT").map(r=>{const q=r.raw_payload||{};return '<tr><td>'+t(r.event_time||r.received_at)+'</td><td>'+n(r.price)+'</td><td>'+n(q.rsi)+'</td><td class="'+(q.trend==="BULL"?"bull":q.trend==="BEAR"?"bear":"neutral")+'">'+txt(q.trend)+'</td><td>'+txt(q.volume_state)+'</td><td>'+n(q.volume_ratio)+'</td><td>'+txt(q.vwap)+'</td><td>'+n(q.vwap_distance)+'</td><td>'+txt(q.or_state)+'</td><td>'+txt(q.vpc_zone)+'</td><td>'+n(q.adr_used_pct)+'</td><td>'+n(q.vix)+'</td><td>'+txt(q.session)+'</td><td>'+n(q.atm_strike)+'</td></tr>'}).join("");
$('events').innerHTML=rows.map(r=>'<tr><td>'+t(r.event_time||r.received_at)+'</td><td>'+txt(r.event)+'</td><td>'+n(r.price)+'</td><td>'+n(r.high)+'</td><td>'+n(r.low)+'</td><td>'+n(r.volume)+'</td><td class="'+cls(r.bias)+'">'+txt(r.bias)+'</td></tr>').join("");
}catch(e){$('status').textContent="● OFFLINE";$('status').style.color="#ff7070";console.error(e)}}refresh();setInterval(refresh,3000);
</script></body></html>`;

function biasFor(event){const e=String(event||"").toUpperCase();if(["BREAKOUT","MOMENTUM","LAUNCHPAD"].some(x=>e.includes(x)))return"BULLISH";if(["BREAKDOWN","EXHAUSTION"].some(x=>e.includes(x)))return"BEARISH";return"WATCH"}
function num(v){if(v===undefined||v===null||v==="")return null;const n=Number(v);return Number.isFinite(n)?n:null}
function parseTime(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
async function initDb(db){await db.prepare(`CREATE TABLE IF NOT EXISTS signals (id INTEGER PRIMARY KEY AUTOINCREMENT,received_at TEXT NOT NULL,event_time TEXT,ticker TEXT NOT NULL,exchange TEXT,timeframe TEXT,event TEXT NOT NULL,price REAL,open REAL,high REAL,low REAL,volume REAL,raw_payload TEXT NOT NULL)`).run()}
async function getSignals(db,limit){const result=await db.prepare(`SELECT id,received_at,event_time,ticker,exchange,timeframe,event,price,open,high,low,volume,raw_payload FROM signals ORDER BY id DESC LIMIT ?`).bind(limit).all();return(result.results||[]).map(r=>({...r,bias:biasFor(r.event),raw_payload:JSON.parse(r.raw_payload)}))}
export default{async fetch(request,env){const url=new URL(request.url),method=request.method.toUpperCase();if(!env.DB)return Response.json({error:"D1 binding DB is missing"},{status:500});await initDb(env.DB);if(url.pathname==="/"&&method==="GET")return new Response(DASHBOARD,{headers:{"content-type":"text/html;charset=UTF-8"}});if(url.pathname==="/api/health"&&method==="GET")return Response.json({status:"ok",service:"sensex-signal-engine",stage:2});if(url.pathname==="/api/latest"&&method==="GET"){const rows=await getSignals(env.DB,1);return Response.json({signal:rows[0]||null})}if(url.pathname==="/api/signals"&&method==="GET"){const requested=Number(url.searchParams.get("limit")||50),limit=Math.max(1,Math.min(Number.isFinite(requested)?requested:50,200));return Response.json({signals:await getSignals(env.DB,limit)})}if(url.pathname==="/webhook/tradingview"&&method==="POST"){let payload;try{payload=await request.json()}catch{return Response.json({error:"Webhook body must be valid JSON"},{status:400})}const ticker=String(payload.ticker||payload.symbol||""),event=String(payload.event||"");if(!ticker||!event)return Response.json({error:"ticker/symbol and event are required"},{status:400});const result=await env.DB.prepare(`INSERT INTO signals (received_at,event_time,ticker,exchange,timeframe,event,price,open,high,low,volume,raw_payload) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(new Date().toISOString(),parseTime(payload.time),ticker,String(payload.exchange||""),String(payload.interval||payload.timeframe||""),event,num(payload.price??payload.close),num(payload.open),num(payload.high),num(payload.low),num(payload.volume),JSON.stringify(payload)).run();return Response.json({status:"accepted",signal_id:result.meta?.last_row_id??null,bias:biasFor(event)})}return Response.json({error:"Not found"},{status:404})}};
